# Generated by Django 3.2.4 on 2021-06-27 19:14

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created at"),
                ),
                ("updated_at", models.DateTimeField(verbose_name="Updated at")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=True, populate_from="name", verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "guide",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="How to Do?",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Image"
                    ),
                ),
                (
                    "start_week",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Start Week"
                    ),
                ),
                (
                    "end_week",
                    models.IntegerField(blank=True, null=True, verbose_name="End Week"),
                ),
                (
                    "preferable_time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                            ("night", "Night"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Chore",
            },
        ),
        migrations.CreateModel(
            name="MarketGarden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created at"),
                ),
                ("updated_at", models.DateTimeField(verbose_name="Updated at")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=9,
                        verbose_name="Length (in meteres)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=9,
                        verbose_name="Width (in meteres)",
                    ),
                ),
                (
                    "path_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.4,
                        max_digits=3,
                        verbose_name="Path Width (in m)",
                    ),
                ),
                (
                    "path_width_btw_sections",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.7,
                        max_digits=3,
                        verbose_name="Path Width between Sections (in m)",
                    ),
                ),
                (
                    "min_bed_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=5.0,
                        max_digits=3,
                        verbose_name="Minimum Bed Length (in m)",
                    ),
                ),
                (
                    "max_bed_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=25.0,
                        max_digits=3,
                        verbose_name="Maximum Bed Length (in m)",
                    ),
                ),
                (
                    "min_bed_per_section",
                    models.IntegerField(
                        blank=True, default=1, verbose_name="Minimum Bed per Section"
                    ),
                ),
                (
                    "max_bed_per_section",
                    models.IntegerField(
                        blank=True, default=10, verbose_name="Maximum Bed per Section"
                    ),
                ),
                (
                    "bed_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Bed Length (in m)",
                    ),
                ),
                (
                    "bed_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.75,
                        max_digits=3,
                        verbose_name="Bed Width (in m)",
                    ),
                ),
                (
                    "bed_along_side_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Side Along which Bed are made",
                    ),
                ),
                (
                    "num_of_bed_along_side",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="No. of Bed Along Side"
                    ),
                ),
                (
                    "num_of_bed_along_otherside",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="No. of Bed Along Otherside"
                    ),
                ),
                (
                    "bed_per_section",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Bed per Section"
                    ),
                ),
                (
                    "total_sections",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Sections"
                    ),
                ),
                (
                    "area_used",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Area Used (in %)",
                    ),
                ),
                (
                    "compost_height_of_bed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.3,
                        max_digits=3,
                        null=True,
                        verbose_name="Compost Height of Bed (in m)",
                    ),
                ),
                (
                    "compost_height_of_path",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.1,
                        max_digits=3,
                        null=True,
                        verbose_name="Compost Height of Path (in m)",
                    ),
                ),
                (
                    "compost_required_per_bed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=9,
                        null=True,
                        verbose_name="Compost Required per Bed (in cu.m)",
                    ),
                ),
                (
                    "total_compost_required",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=9,
                        null=True,
                        verbose_name="Total Compost Required (in cu.m)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Garden",
            },
        ),
        migrations.CreateModel(
            name="MulchingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created at"),
                ),
                ("updated_at", models.DateTimeField(verbose_name="Updated at")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=True, populate_from="name", verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "guide",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="How to Do?",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Image"
                    ),
                ),
                (
                    "start_week",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Start Week"
                    ),
                ),
                (
                    "end_week",
                    models.IntegerField(blank=True, null=True, verbose_name="End Week"),
                ),
                (
                    "bed_new",
                    models.BooleanField(
                        default=True, verbose_name="If Bed New then mulching?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mulching Rule",
            },
        ),
        migrations.CreateModel(
            name="WateringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created at"),
                ),
                ("updated_at", models.DateTimeField(verbose_name="Updated at")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=True, populate_from="name", verbose_name="Slug"
                    ),
                ),
                (
                    "start_week",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Start Week"
                    ),
                ),
                (
                    "end_week",
                    models.IntegerField(blank=True, null=True, verbose_name="End Week"),
                ),
                (
                    "if_rain",
                    models.BooleanField(
                        default=False, verbose_name="If Rain then watering?"
                    ),
                ),
                (
                    "last_watered_at",
                    models.DateTimeField(verbose_name="Last Watered at"),
                ),
                (
                    "lower_temp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=4.0,
                        max_digits=4,
                        verbose_name="Lower Temp. under which watering not required (in deg. C)",
                    ),
                ),
                (
                    "max_hours_for_next_rain",
                    models.IntegerField(
                        blank=True,
                        default=5,
                        verbose_name="Max Hours to check Forecast for Rain",
                    ),
                ),
                (
                    "min_hours_gap_btw_watering",
                    models.IntegerField(
                        blank=True,
                        default=19,
                        verbose_name="Max Hours between Watering",
                    ),
                ),
                (
                    "market_garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_garden.marketgarden",
                        verbose_name="Market Garden",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created at"),
                ),
                ("updated_at", models.DateTimeField(verbose_name="Updated at")),
                ("name", models.CharField(max_length=50, verbose_name="Section Name")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=True, populate_from="name", verbose_name="Slug"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomMulchingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created at"),
                ),
                ("updated_at", models.DateTimeField(verbose_name="Updated at")),
                ("name", models.CharField(max_length=50, verbose_name="Rule Name")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=True, populate_from="name", verbose_name="Slug"
                    ),
                ),
                (
                    "string",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="String value",
                    ),
                ),
                (
                    "numerical",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Numerical value"
                    ),
                ),
                (
                    "boolean",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Boolean value"
                    ),
                ),
                (
                    "parent_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_garden.mulchingrule",
                        verbose_name="Custom Rule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created at"),
                ),
                ("updated_at", models.DateTimeField(verbose_name="Updated at")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Bed Name"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(default=1, verbose_name="Which season?"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_section",
                        to="market_garden.section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
