# Generated by Django 3.2.4 on 2021-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_garden", "0001_market_garden_schemas"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketgarden",
            name="timezone",
            field=models.CharField(blank=True, max_length=100, verbose_name="Timezone"),
        ),
    ]
