# Generated by Django 3.2.4 on 2021-07-21 19:43

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market_garden", "0002_market_garden_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="user",
        ),
        migrations.AddField(
            model_name="section",
            name="market_garden",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="market_garden.marketgarden",
                verbose_name="Market Garden",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="custommulchingrule",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=True, populate_from="name", verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="dailychores",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=True, populate_from="name", verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="mulchingrule",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=True, populate_from="name", verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Section Name"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=True, populate_from="name", verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="wateringrule",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=True,
                populate_from="market_garden",
                verbose_name="Slug",
            ),
        ),
    ]
