# Generated by Django 3.2.4 on 2021-08-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_garden", "0003_alter_section_and_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bed",
            options={"verbose_name_plural": "03 Beds"},
        ),
        migrations.AlterModelOptions(
            name="dailychores",
            options={"verbose_name_plural": "04 Daily Chores"},
        ),
        migrations.AlterModelOptions(
            name="marketgarden",
            options={"verbose_name_plural": "01 Market Gardens"},
        ),
        migrations.AlterModelOptions(
            name="mulchingrule",
            options={"verbose_name_plural": "05 Mulching Rules"},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"verbose_name_plural": "02 Sections"},
        ),
        migrations.AlterModelOptions(
            name="wateringrule",
            options={"verbose_name_plural": "06 Watering Rules"},
        ),
        migrations.AddField(
            model_name="dailychores",
            name="is_specific",
            field=models.BooleanField(
                default=False, verbose_name="Is this a specific market-garden task?"
            ),
        ),
        migrations.AddField(
            model_name="dailychores",
            name="market_garden",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                to="market_garden.MarketGarden",
                verbose_name="Market Garden",
            ),
        ),
        migrations.AlterField(
            model_name="bed",
            name="updated_at",
            field=models.DateTimeField(blank=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="custommulchingrule",
            name="updated_at",
            field=models.DateTimeField(blank=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="dailychores",
            name="preferable_time",
            field=models.IntegerField(
                choices=[
                    (3, "Morning"),
                    (2, "Afternoon"),
                    (1, "Evening"),
                    (0, "Night"),
                ],
                verbose_name="Preferable time for task",
            ),
        ),
        migrations.AlterField(
            model_name="dailychores",
            name="updated_at",
            field=models.DateTimeField(blank=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="marketgarden",
            name="updated_at",
            field=models.DateTimeField(blank=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="mulchingrule",
            name="updated_at",
            field=models.DateTimeField(blank=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="section",
            name="updated_at",
            field=models.DateTimeField(blank=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="wateringrule",
            name="updated_at",
            field=models.DateTimeField(blank=True, verbose_name="Updated at"),
        ),
    ]
