# Generated by Django 3.2.4 on 2021-08-20 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market_garden", "0001_market_garden_schemas"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoWatering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, verbose_name="Updated at"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (3, "Upcoming"),
                            (2, "Started"),
                            (1, "Paused"),
                            (0, "Completed"),
                            (-1, "Over Dued"),
                        ],
                        default=3,
                        verbose_name="Task's status",
                    ),
                ),
                (
                    "market_garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_garden.marketgarden",
                        verbose_name="Market Garden",
                    ),
                ),
                (
                    "watering_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_garden.wateringrule",
                        verbose_name="Watering Rule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "03 Todo Watering",
            },
        ),
        migrations.CreateModel(
            name="TodoMulching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, verbose_name="Updated at"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (3, "Upcoming"),
                            (2, "Started"),
                            (1, "Paused"),
                            (0, "Completed"),
                            (-1, "Over Dued"),
                        ],
                        default=3,
                        verbose_name="Task's status",
                    ),
                ),
                (
                    "market_garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_garden.marketgarden",
                        verbose_name="Market Garden",
                    ),
                ),
                (
                    "mulching_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_garden.mulchingrule",
                        verbose_name="Mulching Rule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "02 Todo Mulching",
            },
        ),
        migrations.CreateModel(
            name="TodoDailyChores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, verbose_name="Updated at"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (3, "Upcoming"),
                            (2, "Started"),
                            (1, "Paused"),
                            (0, "Completed"),
                            (-1, "Over Dued"),
                        ],
                        default=3,
                        verbose_name="Task's status",
                    ),
                ),
                (
                    "daily_chores",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_garden.dailychores",
                        verbose_name="Daily Chores",
                    ),
                ),
                (
                    "market_garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_garden.marketgarden",
                        verbose_name="Market Garden",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "01 Todo Daily Chores",
            },
        ),
    ]
